# SPDX-FileCopyrightText: 2026 Jarkad <jarkad@jarkad.net.eu.org>
#
# SPDX-License-Identifier: EUPL-1.2

version = '2'

[linters]
default = 'all'
disable = [
  'depguard',       # for enterprise scale
  'godox',          # too minor to block commits
  'nonamedreturns', # forbids useful behaviour
  'wsl',            # deprecated
]

[linters.exclusions]
paths = ['(.+)_templ.go']

[[linters.exclusions.rules]]
path = '(.+)_test.go'
linters = [
  'gochecknoglobals', # overzealous
]

[linters.settings.varnamelen]
ignore-decls = [
  'db *sql.DB',
  'db *sqlx.DB',
  'r *http.Request',
  'tx *sql.Tx',
  'tx *sqlx.Tx',
  'w http.ResponseWriter',
]

[formatters]
enable = ['gofmt']
