[tools]
actionlint = "latest"
"aqua:a-h/templ" = "latest"
dbmate = "latest"
gh = "latest"
"github:wimpysworld/tailor" = "latest"
go = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
golangci-lint-langserver = "latest"
goreleaser = "latest"
just = "latest"
"pipx:reuse" = "latest"
sqlc = "latest"
taplo = "latest"
