# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  migrate:
    cmd: dbmate -u sqlite:db.sqlite3 up
    sources:
      - "db/migrations/**/*.sql"

  build:
    cmds:
      - sqlc generate
      - templ generate
      - go mod tidy
      - go build .
    sources:
      - "**/*.go"
      - "**/*.templ"
      - "db/migrations/**/*.sql"
      - "db/queries/**/*.sql"
      - exclude: "**/*_templ.go"
      - exclude: "queries/**/*.go"

  run:
    deps:
      - build
      - migrate
    cmd: ./pocket-expo {{.CLI_ARGS}}

  fmt: treefmt {{.CLI_ARGS}}
  vuln: govulncheck {{.CLI_ARGS}} ./...
