// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counter.sql

package counter

import (
	"context"
)

const decrement = `-- name: Decrement :one
UPDATE counter
SET count = count - 1
RETURNING count
`

func (q *Queries) Decrement(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, decrement)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const get = `-- name: Get :one
SELECT count
FROM counter
`

func (q *Queries) Get(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, get)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const increment = `-- name: Increment :one
UPDATE counter
SET count = count + 1
RETURNING count
`

func (q *Queries) Increment(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, increment)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const reset = `-- name: Reset :exec
DELETE FROM counter
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}
