// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: number.sql

package number

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO counter (count)
VALUES (?)
`

func (q *Queries) Create(ctx context.Context, count int64) error {
	_, err := q.exec(ctx, q.createStmt, create, count)
	return err
}

const deleteAll = `-- name: DeleteAll :exec

DELETE FROM counter
`

// SPDX-FileCopyrightText: 2026 Jarkad <jarkad@jarkad.net.eu.org>
//
// SPDX-License-Identifier: EUPL-1.2
func (q *Queries) DeleteAll(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAllStmt, deleteAll)
	return err
}

const get = `-- name: Get :one
SELECT count
FROM counter
`

func (q *Queries) Get(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getStmt, get)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const set = `-- name: Set :exec
UPDATE counter
SET count = ?
`

func (q *Queries) Set(ctx context.Context, count int64) error {
	_, err := q.exec(ctx, q.setStmt, set, count)
	return err
}
